categories = Category.create([
  {categoryname:"Hotel",categorylao:"ໂຮງແຮມ"},
  {categoryname:"Food",categorylao:"ອາຫານ"},
  {categoryname:"Education",categorylao:"ການສຶກສາ"},
  {categoryname:"Wholesale",categorylao:"ຂາຍສົ່ງ"},
  {categoryname:"Retail",categorylao:"ຂາຍຍ່ອຍ"},
  {categoryname:"Service",categorylao:"ການບໍລິການ"},
  {categoryname:"Construction",categorylao:"ການກໍ່ສ້າງ"},
  {categoryname:"Clinic(Hospital)",categorylao:"ໂຮງໝໍ"},
  {categoryname:"Government Office",categorylao:"ຫ້ອງການລັດ"},
  {categoryname:"Bank",categorylao:"ທະນາຄານ"},
  {categoryname:"Manufactory",categorylao:"ໂຮງງານ"},
  {categoryname:"ransport",categorylao:"ການຂົນສົ່ງ"}
])

cities = City.create([
  {cityname: "Vientiane", city_lao: "ຄອນຫລວງວຽງຈັນ"},
  {cityname: "Luangparbang", city_lao: "ຫຼວງພະບາງ"},
  {cityname: "Champasak", city_lao:"ຈຳປາສັກ"}
])

districts = District.create([
{city_id: 1, districtname:"Parkngeun", district_lao:"ປາກງື່ມ"},
{city_id: 1, districtname:"Sisattanak", district_lao:"ສີສັດຕະນາກ"},
{city_id: 1, districtname:"Sikhottabong", district_lao:"ສີໂຄດຕະບອງ"},
{city_id: 1, districtname:"Chanthabury", district_lao:"ຈັນທະບູລີ"},
{city_id: 1, districtname:"saysettha", district_lao:"ໄຊເສດຖາ"},
{city_id: 1, districtname:"saythany", district_lao:"ໄຊທານີ"},
{city_id: 1, districtname:"Naxaythong", district_lao:"ນາຊາຍທອງ"},
{city_id: 1, districtname:"Hatsaifong", district_lao:"ຫາດຊາຍຟອງ"},
{city_id: 1, districtname:"Sangthong", district_lao:"ສັງທອງ"},

{city_id: 2, districtname:"Luangparbang", district_lao:"ຫຼວງພະບາງ"},
{city_id: 2, districtname:"Xiengngen", district_lao:"ຊຽງເງິນ"},
{city_id: 2, districtname:"Nan", district_lao:"ນານ"},
{city_id: 2, districtname:"Pakou", district_lao:"ປາກອູ"},
{city_id: 2, districtname:"Nambak", district_lao:"ນ້ຳບາກ"},
{city_id: 2, districtname:"Ngoy", district_lao:"ງອຍ"},
{city_id: 2, districtname:"Pakxeng", district_lao:"ປາກແຊງ"},
{city_id: 2, districtname:"Phonxai", district_lao:"ໂພນໄຊ"},
{city_id: 2, districtname:"Chomephet", district_lao:"ຈອມເພັດ"},
{city_id: 2, districtname:"Viengkham", district_lao:"ວຽງຄຳ"},
{city_id: 2, districtname:"Phoukhoun", district_lao:"ພູຄູນ"},
{city_id: 2, districtname:"Phongthon", district_lao:"ໂພນທອງ"},

{city_id: 3, districtname:"Paksa", district_lao:"ປາກເຊ"},
{city_id: 3, districtname:"Sanasomboun", district_lao:"ຊະນະສົມບູນ"},
{city_id: 3, districtname:"Bachiengchaleunsouk", district_lao:"ບາຈຽງຈະເລີນສຸກ"},
{city_id: 3, districtname:"Paksong", district_lao:"ປາກຊ່ອງ"},
{city_id: 3, districtname:"Pathoumphone", district_lao:"ປະທຸມພອນ"},
{city_id: 3, districtname:"Phonthong", district_lao:"ໂພນທອງ"},
{city_id: 3, districtname:"Champasak", district_lao:"ຈຳປາສັກ"},
{city_id: 3, districtname:"Soukhouma", district_lao:"ສຸກຄຸມາ"},
{city_id: 3, districtname:"Meanlapamok", district_lao:"ມິນລະປະໂມກ"},
{city_id: 3, districtname:"Khong", district_lao:"ໂຂງ"}

])

carbrands = Carbrand.create([
  {brandname: "BENZ"},
  {brandname: "BMW"},
  {brandname: "CHANA_CHANGAN"},
  {brandname: "CHERRY_CHERY"},
  {brandname: "GREAT WALL"},
  {brandname: "HONDA"},
  {brandname: "HYUNDAI"},
  {brandname: "KIA"},
  {brandname: "LIFAN"},
  {brandname: "MAZDA"},
  {brandname: "MG"},
  {brandname: "MITSUBISHI"},
  {brandname: "PROTON"},
  {brandname: "TOYOTA"}
])

carmodels = Carmodel.create([
  {brand_id: 1, modelname:"A Class (A45 AMG DC/T)"},
  {brand_id: 1, modelname:"A Class (A200 AMG Sport DC/T)"},
  {brand_id: 1, modelname:"A Class (A250 Sport DC/T)"},
  {brand_id: 1, modelname:"B Class (B180 DC/T)"},
  {brand_id: 1, modelname:"B Class (B200 Sport (Night Package) DC/T)"},
  {brand_id: 1, modelname:"C Class (C200 Avantgarde A/T)"},
  {brand_id: 1, modelname:"C Class (C250 AMG Sport A/T)"},
  {brand_id: 1, modelname:"CLA Class (CLA200 DC/T)"},
  {brand_id: 1, modelname:"CLA Class (CLA250 4Matic DC/T)"},
  {brand_id: 1, modelname:"CLA Class (Coupe)"},
  {brand_id: 1, modelname:"CLS Class (Coupe)"},
  {brand_id: 1, modelname:"E Class (E250 CDI Avantgarde A/T)"},
  {brand_id: 1, modelname:"E Class (E63 AMG DC/T)"},
  {brand_id: 1, modelname:"E Class (Cabriolet)"},
  {brand_id: 1, modelname:"E Class (Coupe)"},
  {brand_id: 1, modelname:"E Class (Sedan)"},
  {brand_id: 1, modelname:"E Class (Wagon)"},
  {brand_id: 1, modelname:"G Class (SUV)"},
  {brand_id: 1, modelname:"G Class (G500 A/T)"},
  {brand_id: 1, modelname:"G Class (G63 AMG A/T)"},
  {brand_id: 1, modelname:"GL Class (GL350 CDI AMG Sport A/T)"},
  {brand_id: 1, modelname:"GL Class (SUV)"},
  {brand_id: 1, modelname:"GLE GLE250d (4MATIC A/T)"},
  {brand_id: 1, modelname:"GLE GLE350d (4MATIC A/T)"},
  {brand_id: 1, modelname:"GLE GLE450 (AMG 4MATIC Coupe A/T)"},
  {brand_id: 1, modelname:"GLA Class (GLA45 AMG DC/T)"},
  {brand_id: 1, modelname:"GLA Class (GLA220 CDI AMG Sport 4Matic DC/T)"},
  {brand_id: 1, modelname:"GLA Class (GLA250 Edition I 4Matic DC/T)"},
  {brand_id: 1, modelname:"GLA Class (SUV)"},
  {brand_id: 1, modelname:"GLC Class (GLC250 4MATIC A/T)"},
  {brand_id: 1, modelname:"GLK Class (SUV)"},
  {brand_id: 1, modelname:"M Class (SUV)"},
  {brand_id: 1, modelname:"Mercedes (AMG GT S)"},
  {brand_id: 1, modelname:"S Class (S500 A/T)"},
  {brand_id: 1, modelname:"S Class (Coupe)"},
  {brand_id: 1, modelname:"S Class (Sedan)"},
  {brand_id: 1, modelname:"SL Class (SL500 A/T)"},
  {brand_id: 1, modelname:"SL Class (SL350 A/T)"},
  {brand_id: 1, modelname:"SL Class (Roadster)"},
  {brand_id: 1, modelname:"SLK Class (SLK200 A/T)"},
  {brand_id: 1, modelname:"SLK Class (SLK250 A/T)"},
  {brand_id: 1, modelname:"SLK Class (SLK350 A/T)"},
  {brand_id: 1, modelname:"SLK Class (SLK55 AMG A/T)"},
  {brand_id: 1, modelname:"SLK Class (Roadster)"},
  {brand_id: 1, modelname:"AMG GT (GT S DC/T)"},
  
  {brand_id: 2, modelname:"BMW X6(xDrive30d Essential A/T)"},
  {brand_id: 2, modelname:"BMW X6(xDrive30d Essential A/T)"},
  {brand_id: 2, modelname:"BMW 1 Series(M135i Hatch A/T)"},
  {brand_id: 2, modelname:"BMW 1 Series(116i Essential A/T)"},
  {brand_id: 2, modelname:"BMW 1 Series(118d Sport Essential A/T)"},
  {brand_id: 2, modelname:"BMW 1 Series(118d Urban Essential A/T)"},
  {brand_id: 2, modelname:"BMW 1 Series(116i Package A/T)"},
  {brand_id: 2, modelname:"BMW 1 Series(118d Urban Package A/T)"},
  {brand_id: 2, modelname:"BMW 1 Series(118d Sport Package A/T)"},
  {brand_id: 2, modelname:"BMW X1(sDrive18 Essential A/T)"},
  {brand_id: 2, modelname:"BMW X1(sDrive18d Package A/T)"},
  {brand_id: 2, modelname:"BMW X1(sDrive18d xLine A/T)"},
  {brand_id: 2, modelname:"BMW X1(sDrive18d Sport A/T)"},
  {brand_id: 2, modelname:"BMW X1(sDrive18d M Sport A/T)"},
  {brand_id: 2, modelname:"BMW 2 Series Coupe (Coupe M235I A/T)"},
  {brand_id: 2, modelname:"BMW 2 Series Coupe (220i Coupe Sport Essential A/T)"},
  {brand_id: 2, modelname:"BMW 2 Series Coupe (220i Coupe Sport Package A/T)"},
  {brand_id: 2, modelname:"BMW 2 Series Active Tourer (218i Active Tourer Essential A/T)"},
  {brand_id: 2, modelname:"BMW 2 Series Active Tourer (218i Active Tourer Package A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series(M3 Sedan Pure M/T)"},
  {brand_id: 2, modelname:"BMW 3 Series(M3 Sedan DC/T)"},
  {brand_id: 2, modelname:"BMW 3 Series(318d Essential A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series(320d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series(318d Package A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series(320d Luxury Package A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series(320d Modern Package A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series(320d Sport Package A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series Gran Turismo (20d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series Gran Turismo (20d Sport Essential A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series Gran Turismo (20d Modern Essential A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series Gran Turismo (20d Sport Package A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series Gran Turismo (20d Luxury Package A/T)"},
  {brand_id: 2, modelname:"BMW 3 Series Gran Turismo (20d Modern Package A/T)"},
  {brand_id: 2, modelname:"BMW X3(sDrive18d SE Essential A/T)"},
  {brand_id: 2, modelname:"BMW X3(xDrive20d xLine Essential A/T)"},
  {brand_id: 2, modelname:"BMW X3(sDrive18d SE Package A/T)"},
  {brand_id: 2, modelname:"BMW X3(XDrive20d xLine Package A/T)"},
  {brand_id: 2, modelname:"BMW 4 Series Coupe(M4 Coupe Pure M/T)"},
  {brand_id: 2, modelname:"BMW 4 Series Coupe(M4 Coupe DC/T)"},
  {brand_id: 2, modelname:"BMW 4 Series Coupe(420d Sport Essential A/T)"},
  {brand_id: 2, modelname:"BMW 4 Series Coupe(420d Sport Package A/T)"},
  {brand_id: 2, modelname:"BMW 4 Series Gran Coupe  (Sport Essential A/T)"},
  {brand_id: 2, modelname:"BMW 4 Series Gran Coupe  (Luxury Essential A/T)"},
  {brand_id: 2, modelname:"BMW 4 Series Gran Coupe  (Luxury Package A/T)"},
  {brand_id: 2, modelname:"BMW 4 Series Gran Coupe  (Sport Package A/T)"},
  {brand_id: 2, modelname:"BMW X4(xDrive20d Essential A/T)"},
  {brand_id: 2, modelname:"BMW X4(xDrive30d Essential A/T)"},
  {brand_id: 2, modelname:"BMW X4(xDrive20d Package A/T)"},
  {brand_id: 2, modelname:"BMW X4(xDrive30d M Sport A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series(520d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series(520d Modern Essential A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series(530d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series(520d Modern Package A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series(520d Luxury Package A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series(530d Luxury Package A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series Gran Turismo(520d Modern Essential A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series Gran Turismo(520d Luxury Essential A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series Gran Turismo(520d Modern Package A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series Gran Turismo(520d Luxury Package A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series Gran Turismo(520d Luxury Package A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series Gran Turismo(530d Luxury A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series Gran Turismo(530d Modern Package A/T)"},
  {brand_id: 2, modelname:"BMW 5 Series Gran Turismo(530d Luxury Package A/T)"},
  {brand_id: 2, modelname:"BMW X5(xDrive30d Essential A/T)"},
  {brand_id: 2, modelname:"BMW X5(xDrive30d Package A/T)"},
  {brand_id: 2, modelname:"BMW X5(xDrive30d Experience A/T)"},
  {brand_id: 2, modelname:"BMW X5(xDrive30d Excellence A/T)"},
  {brand_id: 2, modelname:"BMW X5(xDrive30d M Sport A/T)"},
  {brand_id: 2, modelname:"BMW 6 Series(640i Gran Coupe Essential A/T)"},
  {brand_id: 2, modelname:"BMW 6 Series(640i Gran Coupe Package A/T)"},
  {brand_id: 2, modelname:"BMW 7 Series(730Li A/T)"},
  {brand_id: 2, modelname:"BMW 7 Series(740Li A/T)"},
  {brand_id: 2, modelname:"BMW E24"},
  {brand_id: 2, modelname:"BMW M3"},
  {brand_id: 2, modelname:"BMW M5"},
  {brand_id: 2, modelname:"BMW Z4(Drive20i Essential A/T)"},
  {brand_id: 2, modelname:"BMW Z4(sDrive20i Package A/T)"},
  {brand_id: 2, modelname:"BMW X6M"},

  {brand_id: 3, modelname:"Alsvin Sedan (1.5L)"},
  {brand_id: 3, modelname:"Alsvin Hatchback (1.5L)"},
  {brand_id: 3, modelname:"Alsvin V3 (1.3L)"},
  {brand_id: 3, modelname:"Alsvin V5 (1.5L)"},
  {brand_id: 3, modelname:"Alsvin V7 (1.5/1.6L)"},
  {brand_id: 3, modelname:"Benni (1.0/1.3L)"},
  {brand_id: 3, modelname:"Benni Mini (1.0L)"},
  {brand_id: 3, modelname:"Benni Love (1.3L)"},
  {brand_id: 3, modelname:"CS15 (1.5L)"},
  {brand_id: 3, modelname:"CS35 (1.6L)"},
  {brand_id: 3, modelname:"CS75 (1.8L)"},
  {brand_id: 3, modelname:"CX20 (1.4L)"},
  {brand_id: 3, modelname:"CX30 (1.6/2.0L)"},
  {brand_id: 3, modelname:"CX30 sedan (1.6/2.0L)"},
  {brand_id: 3, modelname:"E30 (pure-electric)"},
  {brand_id: 3, modelname:"Eado (1.6L)"},
  {brand_id: 3, modelname:"Eado EV (pure-electric)"},
  {brand_id: 3, modelname:"Eado XT (1.5/1.6L)"},
  {brand_id: 3, modelname:"Joice (Jiexun) (2.0L)"},
  {brand_id: 3, modelname:"JoiceHEV (1.5L)"},
  {brand_id: 3, modelname:"Raeton (1.8/2.0L)"},
  {brand_id: 3, modelname:"Z-Shine (Zhixiang) (1.6/2.0L)"},
  {brand_id: 3, modelname:"CM8 (1.3L)"},
  {brand_id: 3, modelname:"Eulove (1.2/1.4L)"},
  {brand_id: 3, modelname:"Eulove X6 (1.4L)"},
  {brand_id: 3, modelname:"Honor (1.3/1.5L)"},
  {brand_id: 3, modelname:"Oushang (1.1/1.5L)"},
  {brand_id: 3, modelname:"Ruixing (1.5L)"},
  {brand_id: 3, modelname:"Star (1.2L)"},
  {brand_id: 3, modelname:"Star 2 (1.0L)"},
  {brand_id: 3, modelname:"Star 3 (1.0/1.2L)"},
  {brand_id: 3, modelname:"Star 4500 (1.3L)"},
  {brand_id: 3, modelname:"Star 7 (1.4L)"},
  {brand_id: 3, modelname:"Star 9 (1.5L)"},
  {brand_id: 3, modelname:"Taurustar (1.3L)"},
  {brand_id: 3, modelname:"Zunxing (2.7L)"},

  {brand_id: 4, modelname:"S22L"},
  {brand_id: 4, modelname:"Q22L (Comfortable (11 seater) M/T)"},
  {brand_id: 4, modelname:"Q22B"},
  {brand_id: 4, modelname:"Q22"},
  {brand_id: 4, modelname:"X1"},
  {brand_id: 4, modelname:"Tiggo(2.0 CV/T)"},
  {brand_id: 4, modelname:"Tiggo FL"},
  {brand_id: 4, modelname:"Tiggo 5"},
  {brand_id: 4, modelname:"Arrizo7"},
  {brand_id: 4, modelname:"E5(1.8 CV/T)"},
  {brand_id: 4, modelname:"A3"},
  {brand_id: 4, modelname:"A3 HB"},
  {brand_id: 4, modelname:"E3"},
  {brand_id: 4, modelname:"Fulwin2 FL"},
  {brand_id: 4, modelname:"Fulwin2 FL HB"},
  {brand_id: 4, modelname:"Fulwin 2(1.5 M/T)"},
  {brand_id: 4, modelname:"Fulwin2 HB"},
  {brand_id: 4, modelname:"A1"},
  {brand_id: 4, modelname:"New QQ"},
  {brand_id: 4, modelname:"QQ3(1.0 Luxury M/T)"},

  {brand_id: 5, modelname:"Great Wall Haval H3 (Great Wall Hover / Changcheng Hafu)"},
  {brand_id: 5, modelname:"Great Wall Haval H5"},
  {brand_id: 5, modelname:"Great Wall Haval H6"},
  {brand_id: 5, modelname:"Great Wall Haval H7"},
  {brand_id: 5, modelname:"Great Wall Haval H8"},
  {brand_id: 5, modelname:"Great Wall Haval H9"},
  {brand_id: 5, modelname:"Great Wall Haval M2"},
  {brand_id: 5, modelname:"Great Wall Haval M4"},
  {brand_id: 5, modelname:"Great Wall Deer (Changcheng Dier)"},
  {brand_id: 5, modelname:"Great Wall Steed 3"},
  {brand_id: 5, modelname:"Great Wall Steed 5"},
  {brand_id: 5, modelname:"Great Wall Wingle (Changcheng Fengjun)"},
  {brand_id: 5, modelname:"Great Wall Wingle 5"},
  {brand_id: 5, modelname:"Great Wall Coolbear (Changcheng Kuxiong)"},
  {brand_id: 5, modelname:"Great Wall Florid (Changcheng Xuanli)"},
  {brand_id: 5, modelname:"Great Wall Peri (Changcheng Jingling)"},
  {brand_id: 5, modelname:"Great Wall Haval M1 (Great Wall Peri 4x4)"},
  {brand_id: 5, modelname:"Great Wall Voleex C10 (Great Wall Ling Ao, Phenom, i7)"},
  {brand_id: 5, modelname:"Great Wall Voleex C20R"},
  {brand_id: 5, modelname:"Great Wall Voleex V80 (Great Wall Cowry / Changcheng Jiayu)"},
  {brand_id: 5, modelname:"Great Wall Voleex C30"},
  {brand_id: 5, modelname:"Great Wall Voleex C50"},
  {brand_id: 5, modelname:"Great Wall Voleex C70"},
  {brand_id: 5, modelname:"Great Wall Safe (Changcheng Saifo/Saifu)"},
  {brand_id: 5, modelname:"Great Wall Sailor"},
  {brand_id: 5, modelname:"Great Wall Sing"},
  {brand_id: 5, modelname:"Great Wall SoCool"},
  {brand_id: 5, modelname:"Great Wall Pegasus"},
  {brand_id: 5, modelname:"Great Wall Proteus"},

  {brand_id: 6, modelname:"Honda City(1.5 E M/T"},
  {brand_id: 6, modelname:"Honda City(1.5 E CV/T"},
  {brand_id: 6, modelname:"Honda City(1.5 E NAVI+ M/T"},
  {brand_id: 6, modelname:"Honda City(1.5 E NAVI+ CV/T"},
  {brand_id: 6, modelname:"Honda City(1.5 VX NAVI+ CV/T"},
  {brand_id: 6, modelname:"Honda City(1.5 VX Modulo CV/T"},
  {brand_id: 6, modelname:"Honda City(1.5 VX+ NAVI+ CV/T"},
  {brand_id: 6, modelname:"Honda ZEST (2006-present)"},
  {brand_id: 6, modelname:"Honda Vamos (1970-1973, 1999-present)"},
  {brand_id: 6, modelname:"Honda Stream (2000-present)"},
  {brand_id: 6, modelname:"Honda StepWGN (1996-present)"},
  {brand_id: 6, modelname:"Honda Shuttle (1994-present)"},
  {brand_id: 6, modelname:"Honda Ridgeline (2006-present)"},
  {brand_id: 6, modelname:"Honda Pilot (2003-present)(3.5 EXL A/T)"},
  {brand_id: 6, modelname:"Honda Odyssey/Shuttle (international market) (1995-present)"},
  {brand_id: 6, modelname:"Honda Odyssey (North American market) (1995-present)(2.4 EX-V Navi CV/T)"},
  {brand_id: 6, modelname:"Honda NSX (1990-2005, 2015)"},
  {brand_id: 6, modelname:"Honda N-One (2012-present)"},
  {brand_id: 6, modelname:"Honda MDX (2003-present)"},
  {brand_id: 6, modelname:"Honda Life (1971-1974, 1997-present)"},
  {brand_id: 6, modelname:"Honda Legend (1985-present)(3.5 Sport Hybrid SH-AWD DC/T)"},
  {brand_id: 6, modelname:"Honda Inspire (1990-present)"},
  {brand_id: 6, modelname:"Honda Insight, a hybrid electric vehicle (2000-2006, 2009-present)"},
  {brand_id: 6, modelname:"Honda Jazz(1.5 V M/T)"},
  {brand_id: 6, modelname:"Honda Jazz(1.5 V CV/T)"},
  {brand_id: 6, modelname:"Honda Jazz(1.5 VX CV/T)"},
  {brand_id: 6, modelname:"Honda Jazz(1.5 VX+ CV/T)"},
  {brand_id: 6, modelname:"Honda Fit"},
  {brand_id: 6, modelname:"Honda FCX Clarity"},
  {brand_id: 6, modelname:"Honda CR-V(2.0 V M/T)"},
  {brand_id: 6, modelname:"Honda CR-V(2.0 V A/T)"},
  {brand_id: 6, modelname:"Honda CR-V(2.0 V Cruiser Edition A/T)"},
  {brand_id: 6, modelname:"Honda CR-V(.0 S A/T)"},
  {brand_id: 6, modelname:"Honda CR-V(2.4 SX A/T)"},
  {brand_id: 6, modelname:"Honda Civic(1.8 S M/T)"},
  {brand_id: 6, modelname:"Honda Civic(1.8 S A/T)"},
  {brand_id: 6, modelname:"Honda Civic(1.8 E A/T)"},
  {brand_id: 6, modelname:"Honda Civic(1.8 E Modulo A/T)"},
  {brand_id: 6, modelname:"Honda Civic(2.0 EL A/T)"},
  {brand_id: 6, modelname:"Honda Civic(2.0 EL Mugen A/T)"},
  {brand_id: 6, modelname:"Honda Hobio (2003-present)"},
  {brand_id: 6, modelname:"Honda Freed (2008-present)"},
  {brand_id: 6, modelname:"Honda Fit Aria (1981-present)"},
  {brand_id: 6, modelname:"Honda Elysion (2004-present)"},
  {brand_id: 6, modelname:"Honda Crosstour (2010-present)"},
  {brand_id: 6, modelname:"Honda CR-Z, a hybrid electric vehicle (2011-Present)"},
  {brand_id: 6, modelname:"Honda Civic Hybrid (2003-present)"},
  {brand_id: 6, modelname:"Honda Caren (1990)"},
  {brand_id: 6, modelname:"Honda Brio (2011-present)(1.3 S M/T)"},
  {brand_id: 6, modelname:"Honda Brio (2011-present)(1.3 S A/T)"},
  {brand_id: 6, modelname:"Honda Brio (2011-present)(1.3 V NAVI M/T)"},
  {brand_id: 6, modelname:"Honda Brio (2011-present)(1.3 V NAVI A/T)"},
  {brand_id: 6, modelname:"Honda Brio Amaze(1.3 E M/T)"},
  {brand_id: 6, modelname:"Honda Brio Amaze(1.3 S A/T)"},
  {brand_id: 6, modelname:"Honda Brio Amaze(1.3 V NAVI M/T)"},
  {brand_id: 6, modelname:"Honda Brio Amaze(1.3 V NAVI A/T)"},
  {brand_id: 6, modelname:"Honda Ballade (1982 – present)"},
  {brand_id: 6, modelname:"Honda Airwave (2005-present)"},
  {brand_id: 6, modelname:"Honda Acty (1977-present)"},
  {brand_id: 6, modelname:"Honda Accord (1976-present)(2.4 S A/T)"},
  {brand_id: 6, modelname:"Honda Accord (1976-present)(3.5 SV A/T)"},
  {brand_id: 6, modelname:"Honda Wow"},
  {brand_id: 6, modelname:"Honda Urban SUV"},
  {brand_id: 6, modelname:"Honda SUT"},
  {brand_id: 6, modelname:"Honda Step Bus"},
  {brand_id: 6, modelname:"Honda SSM"},
  {brand_id: 6, modelname:"Honda Small Hybrid Sports"},
  {brand_id: 6, modelname:"Honda S360"},
  {brand_id: 6, modelname:"Honda Remix"},
  {brand_id: 6, modelname:"Honda Puyo"},
  {brand_id: 6, modelname:"Honda OSM"},
  {brand_id: 6, modelname:"Honda N800"},
  {brand_id: 6, modelname:"Honda MV-99"},
  {brand_id: 6, modelname:"Honda Model X"},
  {brand_id: 6, modelname:"Honda Kiwami"},
  {brand_id: 6, modelname:"Honda J-WJ"},
  {brand_id: 6, modelname:"Honda J-VX"},
  {brand_id: 6, modelname:"Honda J-MW"},
  {brand_id: 6, modelname:"Honda J-MJ"},
  {brand_id: 6, modelname:"Honda Imas"},
  {brand_id: 6, modelname:"Honda HSC"},
  {brand_id: 6, modelname:"Honda Gear"},
  {brand_id: 6, modelname:"Honda Fuya-Jo"},
  {brand_id: 6, modelname:"Honda FCX"},
  {brand_id: 6, modelname:"Honda Dualnote (of DN-X) 　"},
  {brand_id: 6, modelname:"Honda CR-Z(1.5 M/T)"},
  {brand_id: 6, modelname:"Honda CR-Z(Modulo M/T)"},
  {brand_id: 6, modelname:"Honda CR-Z(1.5 CV/T)"},
  {brand_id: 6, modelname:"Honda CR-Z(Modulo CV/T)"},
  {brand_id: 6, modelname:"Honda CR-Z(Mugen M/T)"},
  {brand_id: 6, modelname:"Honda CR-Z(Mugen CV/T)"},
  {brand_id: 6, modelname:"Honda ASM"},
  {brand_id: 6, modelname:"Honda 2008 RA108"},
  {brand_id: 6, modelname:"Honda 2007 RA107"},
  {brand_id: 6, modelname:"Honda 2006 RA106"},
  {brand_id: 6, modelname:"Honda 1969 R-1300"},
  {brand_id: 6, modelname:"Honda 1968 RA302"},
  {brand_id: 6, modelname:"Honda 1968 RA301"},
  {brand_id: 6, modelname:"Honda 1967 RA300"},
  {brand_id: 6, modelname:"Honda 1966 RA273"},
  {brand_id: 6, modelname:"Honda 1965 RA272"},
  {brand_id: 6, modelname:"Honda 1964 RA271"},
  {brand_id: 6, modelname:"Honda 1963–1967 T360"},
  {brand_id: 6, modelname:"Honda TN360/TN-III"},
  {brand_id: 6, modelname:"Honda TN-Acty"},
  {brand_id: 6, modelname:"Honda Quint Integra"},
  {brand_id: 6, modelname:"Honda 2004–2009 Honda FR-V, a 6 seater"},
  {brand_id: 6, modelname:"Honda 2004–2009 Edix"},
  {brand_id: 6, modelname:"Honda 2002–2011 Element"},
  {brand_id: 6, modelname:"Honda 2002–2008 Mobilio Spike"},
  {brand_id: 6, modelname:"Honda 2002–2007 That’s"},
  {brand_id: 6, modelname:"Honda 2001–2008 Mobilio  1.5 E M/T"},
  {brand_id: 6, modelname:"Honda 2001–2008 Mobilio  1.5 V CV/T"},
  {brand_id: 6, modelname:"Honda 2001–2008 Mobilio  1.5 RS w/ Nav CV/T"},
  {brand_id: 6, modelname:"Honda 2000–2004 Life Dunk"},
  {brand_id: 6, modelname:"Honda 1999–2009 S2000"},
  {brand_id: 6, modelname:"Honda 1999–2009 S2000"},
  {brand_id: 6, modelname:"Honda 1999–present HR-V  1.8 S CV/T"},
  {brand_id: 6, modelname:"Honda 1999–present HR-V  1.8 E CV/T"},
  {brand_id: 6, modelname:"Honda 1999–present HR-V  1.8 E Modulo CV/T"},
  {brand_id: 6, modelname:"Honda 1999–present HR-V  1.8 EL CV/T"},
  {brand_id: 6, modelname:"Honda 1999–present HR-V  1.8 EL Mugen CV/T"},
  {brand_id: 6, modelname:"Honda 1999–2004 LaGreat"},
  {brand_id: 6, modelname:"Honda 1999–2003 Avancier"},
  {brand_id: 6, modelname:"Honda 1998–2002 Capa"},
  {brand_id: 6, modelname:"Honda 1997–2002 Torneo"},
  {brand_id: 6, modelname:"Honda 1997–1999 EV Plus, an electric vehicle"},
  {brand_id: 6, modelname:"Honda 1996–2010 Partner Van"},
  {brand_id: 6, modelname:"Honda 1996–2002 S-MX"},
  {brand_id: 6, modelname:"Honda 1996–2002 Orthia"},
  {brand_id: 6, modelname:"Honda 1996–2001 Logo"},
  {brand_id: 6, modelname:"Honda 1995–2003 Sabe"},
  {brand_id: 6, modelname:"Honda 1994–2002 Passport"},
  {brand_id: 6, modelname:"Honda 1993–1998, 2008–2010 Crossroad"},
  {brand_id: 6, modelname:"Honda 1993–1997 Rafaga"},
  {brand_id: 6, modelname:"Honda 1992–2004 Domani"},
  {brand_id: 6, modelname:"Honda 1992–1997 CR-X del Sol"},
  {brand_id: 6, modelname:"Honda 1992–1995 NSX-R"},
  {brand_id: 6, modelname:"Honda 1991–1996 Beat"},
  {brand_id: 6, modelname:"Honda 1989–1997 Ascot"},
  {brand_id: 6, modelname:"Honda 1988–1994 Concerto"},
  {brand_id: 6, modelname:"Honda 1985–2007 Integra"},
  {brand_id: 6, modelname:"Honda 1985–1997 Today"},
  {brand_id: 6, modelname:"Honda 1983–1991 CR-X (a.k.a. Ballade Sports CR-X or Civic CR-X)"},
  {brand_id: 6, modelname:"Honda 1981–1999 Street"},
  {brand_id: 6, modelname:"Honda 1980–2002 Ballade"},
  {brand_id: 6, modelname:"Honda 1980–1985 Quintet"},
  {brand_id: 6, modelname:"Honda 1978–2001 Prelude"},
  {brand_id: 6, modelname:"Honda 1973–1974 Life Pick-Up"},
  {brand_id: 6, modelname:"Honda 1972–1974 Life StepVan"},
  {brand_id: 6, modelname:"Honda 1972 1300"},
  {brand_id: 6, modelname:"Honda 1970–1974, 1998–2002 Z"},
  {brand_id: 6, modelname:"Honda 1969–1972 N600"},
  {brand_id: 6, modelname:"Honda 1967–1970 N360/N400"},
  {brand_id: 6, modelname:"Honda 1966–1970 S800"},
  {brand_id: 6, modelname:"Honda 1966–1967 L800"},
  {brand_id: 6, modelname:"Honda 1965–1966 SM600"},
  {brand_id: 6, modelname:"Honda 1965 L700"},
  {brand_id: 6, modelname:"Honda 1964–1967 T500"},
  {brand_id: 6, modelname:"Honda 1964–1966 S600"},
  {brand_id: 6, modelname:"Honda 1963–1964 S500"},
  
  {brand_id: 7, modelname:"Hyundai Tucson(2.0 GL M/T)"},
  {brand_id: 7, modelname:"Hyundai Tucson(2.0 GL A/T)"},
  {brand_id: 7, modelname:"Hyundai Tucson(2.0 GLS A/T)"},
  {brand_id: 7, modelname:"Hyundai Tucson(2.0 R-eVGT GL 4WD A/T)"},
  {brand_id: 7, modelname:"Hyundai New Tucson(2.0 E GL 2WD A/T)"},
  {brand_id: 7, modelname:"Hyundai New Tucson(2.0 S GLS 2WD A/T)"},
  {brand_id: 7, modelname:"Hyundai New Tucson(2.0 S GLS 2WD (dsl) A/T)"},
  {brand_id: 7, modelname:"Hyundai New Tucson(2.0 L 4WD (dsl) A/T)"},
  {brand_id: 7, modelname:"Hyundai Galloper"},
  {brand_id: 7, modelname:"Hyundai Santa Fe(2001–present)(2.2 R-evgt 4×2 M/T)"},
  {brand_id: 7, modelname:"Hyundai Santa Fe(2001–present)(2.2 R-evgt 4×2 A/T)"},
  {brand_id: 7, modelname:"Hyundai Santa Fe(2001–present)(2.2 R-evgt 4×4 A/T)"},
  {brand_id: 7, modelname:"Hyundai Grand Santa Fe(2.2 4WD A/T)"},
  {brand_id: 7, modelname:"Hyundai Terracan"},
  {brand_id: 7, modelname:"Hyundai Trajet"},
  {brand_id: 7, modelname:"Hyundai Accent(1.4 E M/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(1.4 E CV/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(1.6 E (dsl) M/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(1.4 S GL M/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(1.6 E (dsl) A/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(Hatch 1.6 E (dsl) M/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(1.4 S CV/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(1.6 (dsl) DC/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(Hatch 1.6 E (dsl) A/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(1.4 L CV/T)"},
  {brand_id: 7, modelname:"Hyundai Accent(Hatch 1.6 (dsl) DC/T)"},
  {brand_id: 7, modelname:"Hyundai Atos (1997-2007)"},
  {brand_id: 7, modelname:"Hyundai BlueOn"},
  {brand_id: 7, modelname:"Hyundai Dynasty(1996)"},
  {brand_id: 7, modelname:"Hyundai Elantra (1990–present)"},
  {brand_id: 7, modelname:"Hyundai Eon(0.8 GL M/T)"},
  {brand_id: 7, modelname:"Hyundai Eon(0.8 GLS M/T)"},
  {brand_id: 7, modelname:"Hyundai Equus(1999–2016)"},
  {brand_id: 7, modelname:"Hyundai Excel(1985–2000)"},
  {brand_id: 7, modelname:"Hyundai Lavita (2007–2010)"},
  {brand_id: 7, modelname:"Hyundai Genesis (2008–present)"},
  {brand_id: 7, modelname:"Hyundai Genesis Coupe(2008–present)(2.0L FL Turbo A/T)"},
  {brand_id: 7, modelname:"Hyundai Genesis Coupe(2008–present)(2.0L FL Turbo Brembo M/T)"},
  {brand_id: 7, modelname:"Hyundai Genesis Coupe(2008–present)(2.0L FL Turbo A/T)"},
  {brand_id: 7, modelname:"Hyundai Genesis Coupe(2008–present)(3.8L V6 Brembo M/T)"},
  {brand_id: 7, modelname:"Hyundai Getz(2002–2011)"},
  {brand_id: 7, modelname:"Hyundai Grandeur(1986–present)"},
  {brand_id: 7, modelname:"Hyundai HB20(2012–present)"},
  {brand_id: 7, modelname:"Hyundai Grand i10(2007–present)(1.0 E M/T)"},
  {brand_id: 7, modelname:"Hyundai Grand i10(2007–present)(1.0 S M/T)"},
  {brand_id: 7, modelname:"Hyundai Grand i10(2007–present)(1.0 E A/T)"},
  {brand_id: 7, modelname:"Hyundai Grand i10(2007–present)(1.0 S A/T)"},
  {brand_id: 7, modelname:"Hyundai Grand i10(2007–present)(1.0 L A/T)"},
  {brand_id: 7, modelname:"Hyundai Grand i10(2007–present)(1.2 L A/T)"},
  {brand_id: 7, modelname:"Hyundai i20"},
  {brand_id: 7, modelname:"Hyundai i20 Cross Sport(1.4 GL M/T)"},
  {brand_id: 7, modelname:"Hyundai i20 Cross Sport(1.4 GL A/T)"},
  {brand_id: 7, modelname:"Hyundai i20 Cross Sport(1.4 GL (diesel) M/T)"},
  {brand_id: 7, modelname:"Hyundai i20 WRC"},
  {brand_id: 7, modelname:"Hyundai i30(2007–present)"},
  {brand_id: 7, modelname:"Hyundai i40(2011–present)"},
  {brand_id: 7, modelname:"Hyundai ix20(2010–present)"},
  {brand_id: 7, modelname:"Hyundai Mistra(2013–present)"},
  {brand_id: 7, modelname:"Hyundai Scoupe(1988–1995)"},
  {brand_id: 7, modelname:"Hyundai Sonata(1985–present)(2.4 GLS A/T)"},
  {brand_id: 7, modelname:"Hyundai Sonata(1985–present)(2.4 GLS Premium A/T)"},
  {brand_id: 7, modelname:"Hyundai Stellar(1983–1997)"},
  {brand_id: 7, modelname:"Hyundai Veloster(2011-present)"},
  {brand_id: 7, modelname:"Hyundai Veracruz(2007–2015)"},
  {brand_id: 7, modelname:"Hyundai Tiburon(1996–2009)"},
  {brand_id: 7, modelname:"Hyundai Libero"},
  {brand_id: 7, modelname:"Hyundai Porter(1977–present)"},
  {brand_id: 7, modelname:"Hyundai Starex(1997–present)"},
  {brand_id: 7, modelname:"Hyundai Grand Starex(CVX Luxury A/T)"},
  {brand_id: 7, modelname:"Hyundai 4.5 to 5-ton truck"},
  {brand_id: 7, modelname:"Hyundai 8 to 25-ton truck"},
  {brand_id: 7, modelname:"Hyundai Blue-Will"},
  {brand_id: 7, modelname:"Hyundai Nuvis"},
  {brand_id: 7, modelname:"Hyundai Portico"},

 {brand_id: 8, modelname:"Kia Sorento(2.2 EX AWD A/T)"},
 {brand_id: 8, modelname:"Kia KM420"},
 {brand_id: 8, modelname:"Kia Cadenza"},
 {brand_id: 8, modelname:"Kia Rio(1.2L LX 4-DR M/T)"},
 {brand_id: 8, modelname:"Kia Rio(1.2L SLX 4-DR M/T)"},
 {brand_id: 8, modelname:"Kia Rio(1.4L EX 4-DR M/T)"},
 {brand_id: 8, modelname:"Kia Rio(1.4L EX 4-DR A/T)"},
 {brand_id: 8, modelname:"Kia Rio(1.4L EX 5-DR A/T)"},
 {brand_id: 8, modelname:"Kia Picanto(1.0 LX M/T)"},
 {brand_id: 8, modelname:"Kia Picanto(1.0 EX M/T)"},
 {brand_id: 8, modelname:"Kia Picanto(1.2 EX M/T)"},
 {brand_id: 8, modelname:"Kia Rondo"},
 {brand_id: 8, modelname:"Kia Borrego"},
 {brand_id: 8, modelname:"Kia Forte(Sedan 1.6 EX A/T)"},
 {brand_id: 8, modelname:"Kia Forte(Koup 2.0 EX A/T)"},
 {brand_id: 8, modelname:"Kia Forte(5 2.0 SX A/T)"},
 {brand_id: 8, modelname:"Cadenza/K7"},
 {brand_id: 8, modelname:"Venga"},
 {brand_id: 8, modelname:"Soul(1.6 LX CRDI M/T)"},
 {brand_id: 8, modelname:"Soul(1.6 LX CRDI A/T)"},
 {brand_id: 8, modelname:"Rio/Rio5/Pride"},
 {brand_id: 8, modelname:"Rino (expected March 2012)[dated info]"},
 {brand_id: 8, modelname:"Picanto/Morning"},
 {brand_id: 8, modelname:"Optima/Magentis/K5(2.4L EX A/T)"},
 {brand_id: 8, modelname:"K9/Quoris"},
 {brand_id: 8, modelname:"Forte/Cerato"},
 {brand_id: 8, modelname:"Forte Koup"},
 {brand_id: 8, modelname:"Cee’d/Cee’d SW/pro_cee’d"},
 {brand_id: 8, modelname:"Kia Carnival/Sedona(2.2 LWB 11-seater A/T)"},
 {brand_id: 8, modelname:"Kia Carnival/Sedona(2.2 EX LWB A/T)"},
 {brand_id: 8, modelname:"Kia Carens/Rondo(1.7 LX 5-seater A/T)"},
 {brand_id: 8, modelname:"Kia Carens/Rondo(1.7 LX A/T)"},
 {brand_id: 8, modelname:"Kia Carens/Rondo(1.7 EX A/T)"},
 {brand_id: 8, modelname:"Sportage(2.0 EX 4×2 A/T)"},
 {brand_id: 8, modelname:"Sportage(2.0 LX 4×2 A/T)"},
 {brand_id: 8, modelname:"K2700/Strong/3000S/2500TCI- KMC only"},
 {brand_id: 8, modelname:"Granbird – KMC only"},
 {brand_id: 8, modelname:"K4000s – KMC only"},
 {brand_id: 8, modelname:"AM928 – KMC only"},
 {brand_id: 8, modelname:"Kia Soul Hybrid"},
 {brand_id: 8, modelname:"Kia Ray Plug-in hybrid"},
 {brand_id: 8, modelname:"Kia cee’d Hybrid"},
 {brand_id: 8, modelname:"Kia Spectra"},
 {brand_id: 8, modelname:"1974–1981 Kia Brisa"},
 {brand_id: 8, modelname:"Kia Opirus/Amanti"},
 {brand_id: 8, modelname:"Kia Mohave/Borrego"},
 {brand_id: 8, modelname:"2000–2009 Kia Spectra"},
 {brand_id: 8, modelname:"2000–2002 Kia Combi (originally by Asia, since 1983)"},
 {brand_id: 8, modelname:"1995–2001 Kia Credos/Clarus"},
 {brand_id: 8, modelname:"1992–2003 Kia Sephia"},
 {brand_id: 8, modelname:"1987–1996 Kia Concord/Capital"},
 {brand_id: 8, modelname:"1986–2000 Kia Pride"},
 {brand_id: 8, modelname:"1975–1981 Kia Brisa II/K303"},
 {brand_id: 8, modelname:"KCV III"},
 {brand_id: 8, modelname:"Vizen"},
 {brand_id: 8, modelname:"Streetrunner"},
 {brand_id: 8, modelname:"Slice"},
 {brand_id: 8, modelname:"Rondo Taxi"},
 {brand_id: 8, modelname:"Rondo SX"},
 {brand_id: 8, modelname:"Pop"},
 {brand_id: 8, modelname:"Multi S"},
 {brand_id: 8, modelname:"Kue"},
 {brand_id: 8, modelname:"KOUP"},
 {brand_id: 8, modelname:"KND-4"},
 {brand_id: 8, modelname:"Kee"},
 {brand_id: 8, modelname:"KCV-4 Mojave"},
 {brand_id: 8, modelname:"GT"},
 {brand_id: 8, modelname:"Club"},
 {brand_id: 8, modelname:"Alpha"},
 {brand_id: 8, modelname:"18+"},

 {brand_id: 9, modelname:"Lifan 320(Lifan 320 Ex)"},
 {brand_id: 9, modelname:"Lifan 520(Lifan 520 1.6 VIP)"},
 {brand_id: 9, modelname:"Lifan 520(Lifan 520 1.6 LX)"},
 {brand_id: 9, modelname:"Lifan 520(Lifan 520 1.3 LX)"},
 {brand_id: 9, modelname:"Lifan 520(Lifan 520 1.3 DX)"},
 {brand_id: 9, modelname:"Lifan 620(Lifan 620 1.6 LX)"},
 {brand_id: 9, modelname:"Lifan Foison(Lifan Foison 1.3)"},
 {brand_id: 9, modelname:"Lifan Mini Truck(Lifan Mini Truck 1.3)"},

 {brand_id: 10, modelname:"Mazda CX-7"},
 {brand_id: 10, modelname:"Mazda RX-8"},
 {brand_id: 10, modelname:"Mazda MX-5(SKYACTIV-G 2.0 M/T)"},
 {brand_id: 10, modelname:"Mazda MX-5(SKYACTIV-G 2.0 A/T)"},
 {brand_id: 10, modelname:"Mazda Atenza"},
 {brand_id: 10, modelname:"Mazda Axela"},
 {brand_id: 10, modelname:"Mazda Tribute"},
 {brand_id: 10, modelname:"Mazda BT-50(2.2L 4×2 M/T)"},
 {brand_id: 10, modelname:"Mazda BT-50(2.2L 4×2 A/T)"},
 {brand_id: 10, modelname:"Mazda BT-50(3.2L 4×4 A/T)"},
 {brand_id: 10, modelname:"Mazda 2(SkyActiv S Sedan M/T)"},
 {brand_id: 10, modelname:"Mazda 2(SkyActiv S Sedan A/T)"},
 {brand_id: 10, modelname:"Mazda 2(SkyActiv V Hatch A/T)"},
 {brand_id: 10, modelname:"Mazda 2(SkyActiv V Sedan A/T)"},
 {brand_id: 10, modelname:"Mazda 2(SkyActiv R Sedan A/T)"},
 {brand_id: 10, modelname:"Mazda 2(Speed A/T)"},
 {brand_id: 10, modelname:"Mazda 3(1.5 Skyactiv V Sedan A/T)"},
 {brand_id: 10, modelname:"Mazda 3(1.5 Skyactiv V Hatchback A/T)"},
 {brand_id: 10, modelname:"Mazda 3(2.0 Skyactiv R Sedan A/T)"},
 {brand_id: 10, modelname:"Mazda 3(2.0 Skyactiv R Hatchback A/T)"},
 {brand_id: 10, modelname:"Mazda 3(2.0 Speed w/ BOSE A/T)"},
 {brand_id: 10, modelname:"Mazda 6(2.5 A/T)"},
 {brand_id: 10, modelname:"Mazda 6(2.5 Wagon A/T)"},
 {brand_id: 10, modelname:"Mazda CX-5(2.0 MAXX FWD A/T)"},
 {brand_id: 10, modelname:"Mazda CX-5(2.0 Pro FWD A/T)"},
 {brand_id: 10, modelname:"Mazda CX-5(2.5 Sport AWD A/T)"},
 {brand_id: 10, modelname:"Mazda CX-9(3.7L 4×4 AWD A/T)"},
 {brand_id: 10, modelname:"Mazda Takeri"},
 {brand_id: 10, modelname:"Mazda Taiki"},
 {brand_id: 10, modelname:"Mazda Shinari"},
 {brand_id: 10, modelname:"Mazda Senku"},
 {brand_id: 10, modelname:"Mazda Sassou"},
 {brand_id: 10, modelname:"Mazda Ryuga"},
 {brand_id: 10, modelname:"Mazda Nagare"},
 {brand_id: 10, modelname:"Mazda Minagi"},
 {brand_id: 10, modelname:"Mazda Kiyora"},
 {brand_id: 10, modelname:"Mazda Kazamai"},
 {brand_id: 10, modelname:"Mazda Kabura"},
 {brand_id: 10, modelname:"Mazda Kaan"},
 {brand_id: 10, modelname:"Mazda Hakaze"},
 {brand_id: 10, modelname:"Mazda Furai"},
 {brand_id: 10, modelname:"Mazda Activehicle (1999)"},
 {brand_id: 10, modelname:"Mazda MX-5 Superlight (2009)"},
 {brand_id: 10, modelname:"Mazda MX-04 (1987)"},
 {brand_id: 10, modelname:"Mazda MX-03 (1985)"},
 {brand_id: 10, modelname:"Mazda MX-02 (1983)"},
 {brand_id: 10, modelname:"Mazda MV-X (1997"},
 {brand_id: 10, modelname:"Mazda MS-X (1997)"},
 {brand_id: 10, modelname:"Mazda Miata Mono-Posto (1999)"},
 {brand_id: 10, modelname:"Mazda London Taxi (1993)"},
 {brand_id: 10, modelname:"Mazda Le Mans Prototype (1983)"},
 {brand_id: 10, modelname:"Mazda HR-X 2 (1993)"},
 {brand_id: 10, modelname:"Mazda HR-X (1991)"},
 {brand_id: 10, modelname:"Mazda Gissya (1991)"},
 {brand_id: 10, modelname:"Mazda CVS (1974)"},
 {brand_id: 10, modelname:"Mazda CU-X (1995)"},
 {brand_id: 10, modelname:"Mazda BU-X (1995)"},
 {brand_id: 10, modelname:"Mazda AZ550 (1989)"},
 {brand_id: 10, modelname:"Mazda MX-81 (1981)"},
 {brand_id: 10, modelname:"Mazda TD-R (1989)"},
 {brand_id: 10, modelname:"Mazda SW-X (1999)"},
 {brand_id: 10, modelname:"Mazda SU-V (1995)"},
 {brand_id: 10, modelname:"Mazda Secret Hideout (2001)"},
 {brand_id: 10, modelname:"Mazda RX-Evolv (1999)"},
 {brand_id: 10, modelname:"Mazda RX-500 (1970)"},
 {brand_id: 10, modelname:"Mazda RX-01 (1995)"},
 {brand_id: 10, modelname:"Mazda RX 87 (1967)"},
 {brand_id: 10, modelname:"Mazda Nextourer (1999)"},
 {brand_id: 10, modelname:"Mazda Neospace (1999)"},
 {brand_id: 10, modelname:"Mazda MX-Micro Sport (2004)"},
 {brand_id: 10, modelname:"Mazda MX-Flexa (2004)"},
 {brand_id: 10, modelname:"Mazda MX-Crossport (2005)"},
 {brand_id: 10, modelname:"Mazda MX Sportif (2003)"},
 {brand_id: 10, modelname:"Mazda MX Sport Tourier (2001)"},
 
 {brand_id: 11, modelname:"MG 14/28"},
 {brand_id: 11, modelname:"MG 14/40"},
 {brand_id: 11, modelname:"MG 18/80"},
 {brand_id: 11, modelname:"MG M-type Midget"},
 {brand_id: 11, modelname:"MG C-type Midget"},
 {brand_id: 11, modelname:"MG D-type Midget"},
 {brand_id: 11, modelname:"MG F-type Magna"},
 {brand_id: 11, modelname:"MG J-type Midget"},
 {brand_id: 11, modelname:"MG K-type Magnette"},
 {brand_id: 11, modelname:"MG L-type Magna"},
 {brand_id: 11, modelname:"MG N-type Magnette"},
 {brand_id: 11, modelname:"MG P-type Midget"},
 {brand_id: 11, modelname:"MG TA Midget"},
 {brand_id: 11, modelname:"MG TB Midget"},
 {brand_id: 11, modelname:"MG TC Midget"},
 {brand_id: 11, modelname:"MG TD Midget"},
 {brand_id: 11, modelname:"MG TF Midget"},
 {brand_id: 11, modelname:"MGA"},
 {brand_id: 11, modelname:"MG Midget"},
 {brand_id: 11, modelname:"MGB"},
 {brand_id: 11, modelname:"MGC"},
 {brand_id: 11, modelname:"MGB GT V8"},
 {brand_id: 11, modelname:"MG RV8"},
 {brand_id: 11, modelname:"MG F"},
 {brand_id: 11, modelname:"MG TF"},
 {brand_id: 11, modelname:"MG Metro"},
 {brand_id: 11, modelname:"MG ZR"},
 {brand_id: 11, modelname:"MG 3"},
 {brand_id: 11, modelname:"MG KN"},
 {brand_id: 11, modelname:"MG 1100"},
 {brand_id: 11, modelname:"MG 1300"},
 {brand_id: 11, modelname:"MG 14/28"},
 {brand_id: 11, modelname:"MG 14/40"},
 {brand_id: 11, modelname:"MG 18/80"},
 {brand_id: 11, modelname:"MG VA"},
 {brand_id: 11, modelname:"MG Y-type"},
 {brand_id: 11, modelname:"MG Magnette ZA"},
 {brand_id: 11, modelname:"MG Magnette ZB"},
 {brand_id: 11, modelname:"MG Magnette Mk. III"},
 {brand_id: 11, modelname:"MG Magnette Mk. IV"},
 {brand_id: 11, modelname:"MG Maestro"},
 {brand_id: 11, modelname:"MG Montego"},
 {brand_id: 11, modelname:"MG ZS"},
 {brand_id: 11, modelname:"MG 6"},
 {brand_id: 11, modelname:"MG 5"},
 {brand_id: 11, modelname:"MG SA"},
 {brand_id: 11, modelname:"MG WA"},
 {brand_id: 11, modelname:"MG ZT"},
 {brand_id: 11, modelname:"MG 7"},
 {brand_id: 11, modelname:"MG XPower SV"},
 {brand_id: 11, modelname:"MG 18/100 Tigress"},
 {brand_id: 11, modelname:"MG Q-type"},
 {brand_id: 11, modelname:"MG R-type"},
 {brand_id: 11, modelname:"MG EX-E"},
 {brand_id: 11, modelname:"MG Metro van"},
 {brand_id: 11, modelname:"MG Express"},

{brand_id: 12, modelname:"Mitsubishi Montero Sport(GLS 2WD A/T)"},
{brand_id: 12, modelname:"Mitsubishi Montero Sport(GLS Premium 2WD A/T)"},
{brand_id: 12, modelname:"Mitsubishi Montero Sport(GLS 4WD M/T)"},
{brand_id: 12, modelname:"Mitsubishi Montero Sport(GT 4WD A/T)"},
{brand_id: 12, modelname:"Mitsubishi Outlander (Formerly Airtrek)"},
{brand_id: 12, modelname:"Mitsubishi Pajero(GLS 3.8G 4WD A/T)"},
{brand_id: 12, modelname:"Mitsubishi Pajero(GLS 3.2D 4WD A/T)"},
{brand_id: 12, modelname:"Mitsubishi Adventure also known as Mitsubishi Freeca(2.5L TX M/T)"},
{brand_id: 12, modelname:"Mitsubishi Adventure also known as Mitsubishi Freeca(2.5L GX M/T)"},
{brand_id: 12, modelname:"Mitsubishi Adventure also known as Mitsubishi Freeca(2.5L GLX M/T)"},
{brand_id: 12, modelname:"Mitsubishi Adventure also known as Mitsubishi Freeca(2.5L GLS Sport M/T)"},
{brand_id: 12, modelname:"Mitsubishi Adventure also known as Mitsubishi Freeca(2.5L Super Sport M/T)"},
{brand_id: 12, modelname:"Mitsubishi RVR"},
{brand_id: 12, modelname:"Mitsubishi ASX Model(GLS 4×2 CV/T)"},
{brand_id: 12, modelname:"Mitsubishi ASX Model(GSR 4×2 CV/T)"},
{brand_id: 12, modelname:"Mitsubishi Aspire (8th Generation of Galant Model)"},
{brand_id: 12, modelname:"Mitsubishi Carisma (1995–2004)"},
{brand_id: 12, modelname:"Mitsubishi Debonair (1964–1998)"},
{brand_id: 12, modelname:"Mitsubishi Diamante also known as Magna, Sigma, V3000, Verada (1990–2005)"},
{brand_id: 12, modelname:"Mitsubishi Dignity (1999–2001)"},
{brand_id: 12, modelname:"Mitsubishi Emeraude (7th Generation of Galant Model)"},
{brand_id: 12, modelname:"Mitsubishi Eterna Sava (Pillarless Sedan Model)"},
{brand_id: 12, modelname:"Mitsubishi Eterna Sigma (1983–1989)"},
{brand_id: 12, modelname:"Mitsubishi Eterna (5th Generation of Galant Model)"},
{brand_id: 12, modelname:"Mitsubishi Galant"},
{brand_id: 12, modelname:"Mitsubishi Galant Sigma (1969–2012)"},
{brand_id: 12, modelname:"Mitsubishi Galant Sports (1994–1996)"},
{brand_id: 12, modelname:"Mitsubishi Lancer Cedia (2000–2007)"},
{brand_id: 12, modelname:"Mitsubishi Lancer (1973–present)(EX GLX M/T)"},
{brand_id: 12, modelname:"Mitsubishi Lancer (1973–present)(EX GLX A/T)"},
{brand_id: 12, modelname:"Mitsubishi Lancer (1973–present)(EX MX A/T)"},
{brand_id: 12, modelname:"Mitsubishi Lancer (1973–present)(EX GT-A 2.0 CV/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage(1.2 GLX M/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage(1.2 GLX CV/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage(1.2 GLS M/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage(1.2 GLS Special Edition M/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage(1.2 GLS CV/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage G4(G4 GX M/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage G4(G4 GLX M/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage G4(G4 GLX CV/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage G4(G4 GLS M/T)"},
{brand_id: 12, modelname:"Mitsubishi Mirage G4(G4 GLS CV/T)"},
{brand_id: 12, modelname:"Mitsubishi Proudia"},
{brand_id: 12, modelname:"Mitsubishi Sigma"},
{brand_id: 12, modelname:"Mitsubishi Tredia"},
{brand_id: 12, modelname:"Mitsubishi Strada(GL 4×2 M/T)"},
{brand_id: 12, modelname:"Mitsubishi Strada(GLX 4×2 M/T)"},
{brand_id: 12, modelname:"Mitsubishi Strada(GL 4×4 M/T)"},
{brand_id: 12, modelname:"Mitsubishi Strada(GLX V 4×2 A/T)"},
{brand_id: 12, modelname:"Mitsubishi Strada(GLS V 4×4 M/T)"},
{brand_id: 12, modelname:"Mitsubishi Strada(GLS V 4×4 A/T)"},
{brand_id: 12, modelname:"Mitsubishi Libero"},
{brand_id: 12, modelname:"Mitsubishi Delica (1968–present)"},
{brand_id: 12, modelname:"Mitsubishi Cordia (1982–1990)"},
{brand_id: 12, modelname:"Mitsubishi Chariot (1983–2003)"},
{brand_id: 12, modelname:"Mitsubishi Challenger (1996–2008)"},
{brand_id: 12, modelname:"Mitsubishi Eclipse (1989–2011)"},
{brand_id: 12, modelname:"Mitsubishi eK (2001–present)"},
{brand_id: 12, modelname:"Mitsubishi FTO (1994–2000)"},
{brand_id: 12, modelname:"Mitsubishi GTO (1990–2001)"},
{brand_id: 12, modelname:"Mitsubishi i Miev (2009–present)"},
{brand_id: 12, modelname:"Mitsubishi Legnum"},
{brand_id: 12, modelname:"Mitsubishi L200(4X2 (Single Cab Chassis) M/T)"},
{brand_id: 12, modelname:"Mitsubishi L200"},
{brand_id: 12, modelname:"Mitsubishi L300(Deluxe CC w/ FB Body & Dual AC opt. M/T)"},
{brand_id: 12, modelname:"Mitsubishi L300(Exceed CC w/ FB body & Dual AC opt. M/T)"},
{brand_id: 12, modelname:"Mitsubishi L300(Exceed XV Dual AC M/T)"},

{brand_id: 13, modelname:"Proton Saga"},
{brand_id: 13, modelname:"Proton Persona"},
{brand_id: 13, modelname:"Proton Preve"},
{brand_id: 13, modelname:"Proton Inspira"},
{brand_id: 13, modelname:"Proton Iriz"},
{brand_id: 13, modelname:"Proton Satria Neo"},
{brand_id: 13, modelname:"Proton Suprima S"},
{brand_id: 13, modelname:"Proton Exora"},


{brand_id: 14, modelname:"FJ Cruiser Car Review(4×4 A/T)"},
{brand_id: 14, modelname:"Fortuner(2.7 G 4×2 A/T)"},
{brand_id: 14, modelname:"Fortuner(2.5 G 4×2 M/T)"},
{brand_id: 14, modelname:"Fortuner(2.5 G 4×2 A/T)"},
{brand_id: 14, modelname:"Fortuner(2.5 V 4×2 A/T)"},
{brand_id: 14, modelname:"Fortuner(2.5 V (WP) 4×2 A/T)"},
{brand_id: 14, modelname:"Fortuner(3.0 V 4×4 A/T)"},
{brand_id: 14, modelname:"Fortuner(3.0 V (WP) 4×4 A/T)"},
{brand_id: 14, modelname:"Highlander"},
{brand_id: 14, modelname:"Land Cruiser 200(4.5 A/T)"},
{brand_id: 14, modelname:"Land Cruiser 200(4.5 Premium A/T)"},
{brand_id: 14, modelname:"Prado(4.0 VX A/T)"},
{brand_id: 14, modelname:"Prado(3.0 VX Diesel M/T)"},
{brand_id: 14, modelname:"Prado(3.0 VX Diesel A/T)"},
{brand_id: 14, modelname:"Rav4(2.5 Active A/T)"},
{brand_id: 14, modelname:"Rav4(2.5 Active+ A/T)"},
{brand_id: 14, modelname:"Rav4(2.5 Premium A/T)"},
{brand_id: 14, modelname:"Rav4(2.5 Premium AWD A/T)"},
{brand_id: 14, modelname:"Sequoia"},
{brand_id: 14, modelname:"Venza"},
{brand_id: 14, modelname:"Tundra"},
{brand_id: 14, modelname:"Toyota Aygo Small Car"},
{brand_id: 14, modelname:"Allion"},
{brand_id: 14, modelname:"Aurion"},
{brand_id: 14, modelname:"Auris"},
{brand_id: 14, modelname:"Avalon"},
{brand_id: 14, modelname:"Belta"},
{brand_id: 14, modelname:"Camry(2.5 G A/T)"},
{brand_id: 14, modelname:"Camry(2.5 S A/T)"},
{brand_id: 14, modelname:"Camry(2.5 V A/T)"},
{brand_id: 14, modelname:"Camry(3.5 V6 A/T)"},
{brand_id: 14, modelname:"Century"},
{brand_id: 14, modelname:"Corolla Altis(1.6 E M/T)"},
{brand_id: 14, modelname:"Corolla Altis(1.6 G M/T)"},
{brand_id: 14, modelname:"Corolla Altis(1.6 G CV/T)"},
{brand_id: 14, modelname:"Corolla Altis(1.6 V CV/T)"},
{brand_id: 14, modelname:"Corolla Altis(2.0 V CV/T)"},
{brand_id: 14, modelname:"Crown"},
{brand_id: 14, modelname:"Etios"},
{brand_id: 14, modelname:"iQ"},
{brand_id: 14, modelname:"ist"},
{brand_id: 14, modelname:"Mark X"},
{brand_id: 14, modelname:"Matrix"},
{brand_id: 14, modelname:"Premio"},
{brand_id: 14, modelname:"Vios(1.3 Base M/T)"},
{brand_id: 14, modelname:"Vios(1.3 J M/T)"},
{brand_id: 14, modelname:"Vios(1.3 E M/T)"},
{brand_id: 14, modelname:"Vios(1.3 E A/T)"},
{brand_id: 14, modelname:"Vios(1.5 G M/T)"},
{brand_id: 14, modelname:"Vios(1.5 G (WP) M/T)"},
{brand_id: 14, modelname:"Vios(1.5 G A/T)"},
{brand_id: 14, modelname:"Vios(1.5 G (WP) A/T)"},
{brand_id: 14, modelname:"Wigo(1.0 E M/T)"},
{brand_id: 14, modelname:"Wigo(1.0 G M/T)"},
{brand_id: 14, modelname:"Wigo(1.0 G A/T)"},
{brand_id: 14, modelname:"Yaris(1.3 E M/T)"},
{brand_id: 14, modelname:"Yaris(1.3 E A/T)"},
{brand_id: 14, modelname:"Yaris(1.5 G A/T)"},
{brand_id: 14, modelname:"Vitz"},
{brand_id: 14, modelname:"Avensis"},
{brand_id: 14, modelname:"Avanza(1.3 J M/T)"},
{brand_id: 14, modelname:"Avanza(1.3 E M/T)"},
{brand_id: 14, modelname:"Avanza(1.3 E A/T)"},
{brand_id: 14, modelname:"Avanza(1.5 G M/T)"},
{brand_id: 14, modelname:"Avanza(1.5 G A/T)"},
{brand_id: 14, modelname:"bB"},
{brand_id: 14, modelname:"Condor"},
{brand_id: 14, modelname:"Comfort"},
{brand_id: 14, modelname:"Innova(2.0 J M/T)"},
{brand_id: 14, modelname:"Innova(2.5 J M/T)"},
{brand_id: 14, modelname:"Innova(2.0 E M/T)"},
{brand_id: 14, modelname:"Innova(2.5 E M/T)"},
{brand_id: 14, modelname:"Innova(2.0 E A/T)"},
{brand_id: 14, modelname:"Innova(2.0 G M/T)"},
{brand_id: 14, modelname:"Innova(2.5 E A/T)"},
{brand_id: 14, modelname:"Innova(2.5 G M/T"},
{brand_id: 14, modelname:"Innova(2.0 G A/T)"},
{brand_id: 14, modelname:"Innova(2.5 G A/T)"},
{brand_id: 14, modelname:"Innova(2.0 V A/T)"},
{brand_id: 14, modelname:"Innova(2.5 V A/T)"},
{brand_id: 14, modelname:"Ipsum"},
{brand_id: 14, modelname:"Isis"},
{brand_id: 14, modelname:"Noah"},
{brand_id: 14, modelname:"Porte"},
{brand_id: 14, modelname:"Ractis"},
{brand_id: 14, modelname:"Raum"},
{brand_id: 14, modelname:"Sienta"},
{brand_id: 14, modelname:"Verso"},
{brand_id: 14, modelname:"Alphard(3.5 A/T)"},
{brand_id: 14, modelname:"Coaster"},
{brand_id: 14, modelname:"Hiace(Commuter 2.5L M/T)"},
{brand_id: 14, modelname:"Hiace(GL Grandia 2.5L M/T)"},
{brand_id: 14, modelname:"Hiace(GL Grandia 2.5L A/T)"},
{brand_id: 14, modelname:"Hiace(Super Grandia (Fabric) A/T)"},
{brand_id: 14, modelname:"Hiace(Super Grandia (Leather) A/T)"},
{brand_id: 14, modelname:"Hiace(LXV A/T)"},
{brand_id: 14, modelname:"Hilux(2.4 J 4×2 M/T)"},
{brand_id: 14, modelname:"Hilux(2.4 E 4×2 M/T)"},
{brand_id: 14, modelname:"Hilux(2.4 G 4×2 M/T)"},
{brand_id: 14, modelname:"Hilux(2.4 G 4×2 A/T)"},
{brand_id: 14, modelname:"Hilux(2.8 G 4×4 M/T)"},
{brand_id: 14, modelname:"Hilux(2.8 G 4×4 A/T)"},
{brand_id: 14, modelname:"Previa(2.4 A/T)"},
{brand_id: 14, modelname:"Previa(2.4 (WP) A/T)"},
{brand_id: 14, modelname:"Previa(2.4 Q A/T)"},
{brand_id: 14, modelname:"Previa(2.4 Q (WP) A/T)"},
{brand_id: 14, modelname:"Sienna"},
{brand_id: 14, modelname:"Tacoma"},
{brand_id: 14, modelname:"Wish"},
{brand_id: 14, modelname:"Prius(1.8 Hybrid CV/T)"},
{brand_id: 14, modelname:"Prius(1.8 Hybrid (WP) CV/T)"},
{brand_id: 14, modelname:"Prius C(1.5 Standard CV/T)"},
{brand_id: 14, modelname:"Prius C(1.5 Full Option CV/T)"},
{brand_id: 14, modelname:"Sai"},
{brand_id: 14, modelname:"86(2.0 M/T)"},
{brand_id: 14, modelname:"86(2.0 (WP) M/T)"},
{brand_id: 14, modelname:"86(2.0 A/T)"},
{brand_id: 14, modelname:"86(2.0 (WP) A/T)"},
{brand_id: 14, modelname:"86(2.0 Aero M/T)"},
{brand_id: 14, modelname:"86(2.0 Aero (WP) M/T)"},
{brand_id: 14, modelname:"86(2.0 Aero A/T)"},
{brand_id: 14, modelname:"86(2.0 Aero (WP) A/T)"},
{brand_id: 14, modelname:"Sera (1990-1995)"},
{brand_id: 14, modelname:"Paseo (1991-1999)"},
{brand_id: 14, modelname:"Tercel (1978-1999)"},
{brand_id: 14, modelname:"Starlet (1973-1999)"},
{brand_id: 14, modelname:"Celica"},
{brand_id: 14, modelname:"Supra"},
{brand_id: 14, modelname:"Carina"},
{brand_id: 14, modelname:"MR2"}


])




users = User.create([
  {
    email: 'testor@gmail.com',
    name: 'bestbot',
    password: '5d93ceb70e2bf5daa84ec3d0cd2c731a',
    sex: 'f',
    tel: '01122223333',
    birthdate: '19991111',
    usertype: 'user'
  },
  {
    email: 'carpenta@hanmail.net',
    name: 'ilhwan',
    password: '5d93ceb70e2bf5daa84ec3d0cd2c731a',
    sex: 'm',
    tel: '01026092841',
    birthdate: '19991111',
    usertype: 'user'
  },
  {
    email: 'mc2e@nate.com',
    name: 'kyungkoo',
    password: '5d93ceb70e2bf5daa84ec3d0cd2c731a',
    sex: 'm',
    tel: '01033334444',
    birthdate: '19991111',
    usertype: 'company',
    marketname: 'sample market',
    marketphone: 'sample phone', 
    marketemail: 'market@sample.com',
    address: 'sample marekt address'
  }
])

markets = Market.create([
  {
    marketname: 'beuty shop',
    marketname_lao: 'beuty shop ບັນຊ',
    user_id: 1,
    category1: 'Accountants',
    category2: 'Transport Services',
    city: 'test city',
    district: 'test  district',
    address: 'test address',
    address_lao: 'test address lao',
    open1: '10:00',
    close1: '19:00',
    desc1: 'MON,TUE',
    open2: '9:00',
    close2: '15:00',
    desc2: 'THU, FRI',
    open3: '14:00',
    close3: '18:00',
    desc3: 'SAT, SUN',
    fax: '111-2222-2222',
    cellphone: '333-4444-4444',
    tel: '123-452-1134',
    email: '1@1.2',
    homepage: 'test.hompage.com',
    latitude: '21.2312321312',
    longitude: '32.42132132',
    delyn: 'no',
    detail_lao: 'detail lao test',
    detail_eng: 'detail eng test',
    keyword: 'testkeyword',
    keyword_lao: 'testkeyword_ບັນຊ'
  }
])

rooms = Room.create([
  {
    roomname: 'sample room',
    roomname_lao: 'sample room ບັນຊ',
    user_id: 1,
    address: 'test address',
    address_lao: 'test address lao',
    cellphone: '333-4444-4444',
    tel: '123-452-1134',
    email: '1@1.2',
    latitude: '21.2312321312',
    longitude: '32.42132132',
    delyn: 'no',
    detail_lao: 'detail lao test',
    detail_eng: 'detail eng test',
    deposit: 2000,
    rent: 101,
    rstruct: 'one room',
    rcount: 1,
    bcount: 1,
    bform: 'apartment',
    bfloor: 3,
    parea: 11,
    aarea: 12,
    options: 'sink, air con',
    mexpenses: 100,
    livedays: 90,
    parkingyn: 'yes',
    elevatoryn: 'no',
    poolyn: 'no'
  }
])


favorites = Favorite.create([
  {
    user_id: 1,
    car_id: 1
  }
])
